function Save-AiNativeUnityGeneratedState {
    param([Parameter(Mandatory)][string]$ProjectRoot)
    $root = [IO.Path]::GetFullPath($ProjectRoot)
    $files = @{}
    foreach ($file in Get-ChildItem -LiteralPath $root -File) {
        if ($file.Extension -in @('.csproj','.sln','.slnx')) {
            $files[$file.Name] = [IO.File]::ReadAllBytes($file.FullName)
        }
    }
    $normalizedAssets = @{}
    foreach ($relative in @('ProjectSettings/ShaderGraphSettings.asset','ProjectSettings/GraphicsSettings.asset',
        'Assets/AiNative.BattleClient/Rendering/BattleClientPipeline.asset','Assets/UniversalRenderPipelineGlobalSettings.asset')) {
        $path = Join-Path $root $relative
        if (Test-Path -LiteralPath $path -PathType Leaf) { $normalizedAssets[$relative]=[IO.File]::ReadAllBytes($path) }
    }
    return [pscustomobject]@{Root=$root; Files=$files; NormalizedAssets=$normalizedAssets}
}

function Restore-AiNativeUnityGeneratedState {
    param([Parameter(Mandatory)]$Snapshot)
    $restored = [Collections.Generic.List[string]]::new()
    foreach ($name in $Snapshot.Files.Keys) {
        $path = [IO.Path]::GetFullPath((Join-Path $Snapshot.Root $name))
        if ([IO.Path]::GetDirectoryName($path) -ne $Snapshot.Root) { throw 'Generated file escapes Unity project root' }
        [IO.File]::WriteAllBytes($path,$Snapshot.Files[$name])
        $restored.Add($name)
    }
    # These two local Fantasy assemblies are generated by Unity, absent from older project inventories.
    foreach ($name in @('Fantasy.Editor.csproj','Fantasy.Unity.csproj')) {
        $path = [IO.Path]::GetFullPath((Join-Path $Snapshot.Root $name))
        if ([IO.Path]::GetDirectoryName($path) -ne $Snapshot.Root) { throw 'Generated file escapes Unity project root' }
        if (-not $Snapshot.Files.ContainsKey($name) -and (Test-Path -LiteralPath $path -PathType Leaf)) {
            if ([IO.File]::ReadAllText($path) -notmatch 'Generated file, do not modify') { throw "Refusing to remove unknown project file: $path" }
            Remove-Item -LiteralPath $path
            $restored.Add($name)
        }
    }
    foreach ($relative in $Snapshot.NormalizedAssets.Keys) {
        $path = Join-Path $Snapshot.Root $relative
        $before = [Text.Encoding]::UTF8.GetString($Snapshot.NormalizedAssets[$relative]).TrimStart([char]0xfeff).Replace("`r`n","`n")
        $after = [IO.File]::ReadAllText($path).Replace("`r`n","`n")
        if ($before -cne $after) { throw "Unity changed $relative beyond line endings; preserve and review the change" }
        [IO.File]::WriteAllBytes($path,$Snapshot.NormalizedAssets[$relative])
        $restored.Add($relative)
    }
    return $restored.ToArray()
}
